name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build samples/csharp_dotnetcore/80.skills-simple-bot-to-bot/SimpleBotToBot.sln --configuration Release
    - name: Publish with dotnet
      run: dotnet publish samples/csharp_dotnetcore/80.skills-simple-bot-to-bot/SimpleBotToBot.sln --configuration Release
